# Generated by Django 4.2.1 on 2023-05-15 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plane', models.CharField(max_length=250)),
                ('town_from', models.CharField(max_length=250)),
                ('town_to', models.CharField(max_length=250)),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Pass_in_trip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=250)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes_app.passenger')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes_app.trip')),
            ],
        ),
    ]
